# This is an example daemon_settings.yml file.
# See https://lbry.tech/resources/daemon-settings for all configuration keys and values

share_usage_data: True

lbryum_servers:
  - lbryumx1.lbry.io:50001
  - lbryumx2.lbry.io:50001

blockchain_name: lbrycrd_main

data_dir: /home/lbry/.lbrynet
download_directory: /home/lbry/downloads

save_blobs: true
streaming_only: false
dht_node_port: 4444
peer_port: 3333
use_upnp: true

#components_to_skip:
#  - hash_announcer
#  - blob_server
#  - dht
